#!/usr/bin/env bash
rm -r node_modules
yarn install

# I edited the material-ui package to include Sliders with tooltips
# so let's copy the edit over
cp src/package_edits/Slider.js node_modules/material-ui/Slider/Slider.js

# We don't have wget or git by default on OS X, so let's get it with Homebrew
if [[ "$OSTYPE" == "darwin"* ]]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install wget
    brew install git
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
    apt-get install wget  # sometimes wget may not be installed already
    apt-get install git
fi

# Install swipl from source
wget http://www.swi-prolog.org/download/stable/src/swipl-7.6.3.tar.gz
tar xzvf swipl-7.6.3.tar.gz
cd swipl-7.6.3 || exit
CFLAGS=-ggdb ./configure --enable-shared
make && make install

# Install pyswip from GitHub
git clone https://github.com/yuce/pyswip
cd pyswip || exit
python setup.py install
